[0m18:19:42.738405 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277B3823C50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277B3823050>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277B3820810>]}


============================== 18:19:42.742770 | 4fe6ea72-0d17-4a9e-9ec2-5a5278889e0a ==============================
[0m18:19:42.742770 [info ] [MainThread]: Running with dbt=1.8.9
[0m18:19:42.743386 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Sandy Lauguico\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'empty': 'None', 'quiet': 'False', 'no_print': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt init', 'send_anonymous_usage_stats': 'True'}
[0m18:28:29.828157 [debug] [MainThread]: Starter project path: C:\Users\Sandy Lauguico\Documents\01-learn-in-public\product\ecommerce-modern-data-stack\venv\Lib\site-packages\dbt\include\starter_project
[0m18:28:29.923648 [info ] [MainThread]: 
Your new dbt project "ecom_data_model" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m18:28:29.924968 [info ] [MainThread]: Setting up your profile.
[0m18:36:50.312660 [info ] [MainThread]: Profile ecom_data_model written to C:\Users\Sandy Lauguico\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m18:36:50.315087 [debug] [MainThread]: Command `dbt init` succeeded at 18:36:50.315087 after 1027.67 seconds
[0m18:36:50.315087 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277AD24C510>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277AD31FB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000277AD5ADD90>]}
[0m18:36:50.316294 [debug] [MainThread]: Flushing usage events
[0m18:37:33.388928 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209411984D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020941198650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020941199650>]}


============================== 18:37:33.394921 | bf534216-f8a4-4ca7-b812-51b80787d05a ==============================
[0m18:37:33.394921 [info ] [MainThread]: Running with dbt=1.8.9
[0m18:37:33.396899 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Sandy Lauguico\\.dbt', 'fail_fast': 'False', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'invocation_command': 'dbt run --select ecom_data_model/models/staging/', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m18:37:33.396899 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Sandy Lauguico\Documents\01-learn-in-public\product\ecommerce-modern-data-stack\ecom_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:37:33.398904 [debug] [MainThread]: Command `dbt run` failed at 18:37:33.398904 after 0.12 seconds
[0m18:37:33.398904 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209411D4110>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000209411D5410>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000020941199910>]}
[0m18:37:33.399995 [debug] [MainThread]: Flushing usage events
[0m18:38:30.698891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278F84A8450>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278F84A8310>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278F84AA2D0>]}


============================== 18:38:30.702469 | 1fc65c9b-12a2-42da-8cc8-39fb1a2d21bc ==============================
[0m18:38:30.702469 [info ] [MainThread]: Running with dbt=1.8.9
[0m18:38:30.702891 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Sandy Lauguico\\.dbt', 'fail_fast': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'static_parser': 'True', 'introspect': 'True', 'invocation_command': 'dbt run --select ecom_data_model/models/staging/', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m18:38:30.702891 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Sandy Lauguico\Documents\01-learn-in-public\product\ecommerce-modern-data-stack\ecom_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m18:38:30.704392 [debug] [MainThread]: Command `dbt run` failed at 18:38:30.704392 after 0.06 seconds
[0m18:38:30.704392 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278F84DCFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278F84DD290>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000278F84DD3D0>]}
[0m18:38:30.705008 [debug] [MainThread]: Flushing usage events
[0m19:32:30.949952 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017F9838BF50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017F98389810>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017F98388210>]}


============================== 19:32:30.960096 | 35e23213-aefe-49f5-a95a-6a613ec85037 ==============================
[0m19:32:30.960096 [info ] [MainThread]: Running with dbt=1.8.9
[0m19:32:30.961107 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'profiles_dir': 'C:\\Users\\Sandy Lauguico\\.dbt', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'None', 'log_format': 'default', 'introspect': 'True', 'invocation_command': 'dbt deps', 'static_parser': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m19:32:30.962107 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Sandy Lauguico\Documents\01-learn-in-public\product\ecommerce-modern-data-stack\ecom_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m19:32:30.965430 [debug] [MainThread]: Command `dbt deps` failed at 19:32:30.965430 after 0.08 seconds
[0m19:32:30.965430 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017F91DBCB90>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017F983CBE10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000017F983CBC10>]}
[0m19:32:30.965430 [debug] [MainThread]: Flushing usage events
[0m13:11:07.583524 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227D0C2C090>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227D0C2E6D0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227D0C2E690>]}


============================== 13:11:07.592516 | c1eda2b3-3d60-4d04-a06d-28df3e79dda0 ==============================
[0m13:11:07.592516 [info ] [MainThread]: Running with dbt=1.8.9
[0m13:11:07.593814 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Sandy Lauguico\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'version_check': 'True', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'empty': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'invocation_command': 'dbt run --select models/ecom_marts/', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m13:11:07.593814 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Sandy Lauguico\Documents\01-learn-in-public\product\ecommerce-modern-data-stack\ecom_dbt\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m13:11:07.595002 [debug] [MainThread]: Command `dbt run` failed at 13:11:07.595002 after 0.09 seconds
[0m13:11:07.596106 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227D0C5C750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227D0C5B750>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000227D0C49650>]}
[0m13:11:07.596246 [debug] [MainThread]: Flushing usage events
